language: node_js
node_js:
  - "14.2.0"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
  - npm install
script:
  - ng build --prod
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
